"""Submission hygiene audit. Development infrastructure - NOT part of the ZIP.

Checks the exact files destined for the archive for accidental development
traces: tool references, conversational or instruction-like prose, debug
artefacts, machine-specific paths, unusual notebook or PDF metadata, hidden PDF
content, stale outputs, and unwanted files.

Findings are graded CRITICAL (must be zero) or REVIEW (needs a human decision,
because the word can be legitimate in technical writing).
"""
import json
import re
import sys
from pathlib import Path

ZIP_CONTENTS = [
    "Problem_Set_3_Report.pdf",
    "Problem_Set_3_Notebook.ipynb",
    "mlp.py",
    "README.md",
    "requirements.txt",
    "data/nyc-yellow-may2oct.csv",
] + sorted(f"results/{p.name}" for p in Path("results").glob("*.csv"))

CRITICAL = {
    "AI/tool reference": r"(?i)\b(claude|anthropic|chatgpt|openai|gpt-?[0-9]|copilot|"
                         r"ai[- ]generated|generated by (?:an? )?(?:ai|model|assistant)|"
                         r"as an ai|system prompt|chain[- ]of[- ]thought)\b",
    "development tooling": r"(?i)\b(scratchpad|smoke[- ]test|build_notebook|build_report|"
                           r"audit_submission|results_registry|p2_lib|nohup|"
                           r"background task|failed run)\b",
    "conversational prose": r"(?i)(say the word|let me (?:know|check|run|fix)|"
                            r"i'?ll (?:check|run|fix|now)|i will now|waiting for|"
                            r"shall i\b|as you asked|you asked me|your instruction|"
                            r"next i will|before i continue|here is the audit|"
                            r"proceeding to)",
    "debug marker": r"(?i)\b(todo|fixme|xxx+|hack:|pdb\.set_trace|breakpoint\(\)|"
                    r"print\(['\"]debug)",
    "machine path": r"(?i)([A-Z]:[\\/]Users[\\/]|/c/Users/|/home/[a-z_]+/|/mnt/data/|"
                    r"AppData[\\/]Local[\\/]Temp|OneDrive|[\\/]Downloads[\\/]|"
                    r"[\\/]Desktop[\\/])",
}

# Words that are legitimate in technical writing but worth eyeballing.
REVIEW = {
    "possibly-dev wording": r"(?i)\b(scratch|temporary|workaround|retry|monitor|"
                            r"builder|registry|internal|diagnostic|stale)\b",
    "instruction-like": r"(?i)^(do not|please verify|you should|now implement|"
                        r"first inspect)\b",
}


def find(text, patterns):
    out = []
    lines = text.splitlines()
    for label, pat in patterns.items():
        for m in re.finditer(pat, text, re.MULTILINE):
            ln = text.count("\n", 0, m.start()) + 1
            ctx = lines[ln - 1].strip()[:120] if ln - 1 < len(lines) else ""
            out.append((label, ln, m.group(0), ctx))
    return out


def report(kind, name, where, hits):
    for label, ln, tok, ctx in hits:
        print(f"    {kind:8s} [{label}] {where} line {ln}: '{tok}'")
        print(f"             | {ctx}")


def audit_text_file(path):
    txt = Path(path).read_text(encoding="utf-8", errors="replace")
    c = find(txt, CRITICAL)
    r = find(txt, REVIEW)
    report("CRITICAL", path, "", c)
    report("REVIEW", path, "", r)
    return len(c), len(r)


def audit_notebook(path):
    raw = Path(path).read_text(encoding="utf-8")
    nb = json.loads(raw)
    ncrit = nrev = 0
    code = [c for c in nb["cells"] if c["cell_type"] == "code"]

    print("  execution integrity")
    counts = [c.get("execution_count") for c in code]
    seq = counts == list(range(1, len(code) + 1))
    print(f"    cells={len(nb['cells'])}  code={len(code)}")
    print(f"    execution counts sequential 1..{len(code)}: {seq}")
    unrun = [i for i, c in enumerate(counts) if c is None]
    print(f"    unrun code cells: {unrun or 'none'}")
    errs = [i for i, c in enumerate(code)
            if any(o.get("output_type") == "error" for o in c.get("outputs", []))]
    print(f"    cells with error output: {errs or 'none'}")
    noout = [i for i, c in enumerate(code) if not c.get("outputs")]
    print(f"    code cells with no output: {noout or 'none'}")

    print("  metadata")
    top = set(nb.get("metadata", {}))
    print(f"    notebook-level keys: {sorted(top)}")
    unusual_top = top - {"kernelspec", "language_info"}
    print(f"    non-standard notebook metadata: {sorted(unusual_top) or 'none'}")
    cellmeta = {i: sorted(c.get("metadata", {}))
                for i, c in enumerate(nb["cells"]) if c.get("metadata")}
    print(f"    cells carrying metadata: {cellmeta or 'none'}")
    atts = [i for i, c in enumerate(nb["cells"]) if c.get("attachments")]
    print(f"    cells with attachments: {atts or 'none'}")

    print("  content scan")
    for i, c in enumerate(nb["cells"]):
        src = "".join(c["source"])
        hc, hr = find(src, CRITICAL), find(src, REVIEW)
        report("CRITICAL", path, f"cell {i} src", hc)
        report("REVIEW", path, f"cell {i} src", hr)
        ncrit += len(hc); nrev += len(hr)
        for o in c.get("outputs", []):
            txt = ""
            if o.get("output_type") == "stream":
                txt = "".join(o.get("text", []))
                if o.get("name") == "stderr":
                    print(f"    NOTE stderr output in cell {i}: "
                          f"{txt.strip()[:160]}")
            elif o.get("output_type") in {"execute_result", "display_data"}:
                txt = "".join(o.get("data", {}).get("text/plain", []))
            hc, hr = find(txt, CRITICAL), find(txt, REVIEW)
            report("CRITICAL", path, f"cell {i} OUT", hc)
            report("REVIEW", path, f"cell {i} OUT", hr)
            ncrit += len(hc); nrev += len(hr)
    return ncrit, nrev


def audit_pdf(path):
    try:
        import fitz
    except ImportError:
        print("    (PyMuPDF unavailable)")
        return 0, 0
    doc = fitz.open(path)
    print(f"  pages: {len(doc)}")
    print("  metadata")
    for k, v in (doc.metadata or {}).items():
        print(f"    {k:14s}: {v!r}")
    md = json.dumps(doc.metadata or {})
    hc = find(md, CRITICAL)
    report("CRITICAL", path, "metadata", hc)

    print("  embedded/hidden content")
    print(f"    embedded files: {doc.embfile_count()}")
    n_annot = sum(1 for p in doc for _ in p.annots())
    n_links = sum(len(p.get_links()) for p in doc)
    print(f"    annotations: {n_annot}   links: {n_links}")
    raw = raw_pdf_bytes(path)
    for token in ("/JavaScript", "/JS", "/Launch", "/EmbeddedFile", "/RichMedia"):
        print(f"    token {token:14s} present in file: {token in raw}")
    print(f"    optional content groups (layers): "
          f"{list((doc.get_ocgs() or {}).keys()) or 'none'}")

    txt = "".join(p.get_text() for p in doc)
    print(f"  extracted text: {len(txt):,} chars")
    repl = txt.count("�")
    print(f"    replacement characters (U+FFFD): {repl}")
    ht = find(txt, CRITICAL)
    hr = find(txt, REVIEW)
    report("CRITICAL", path, "text", ht)
    report("REVIEW", path, "text", hr)
    for marker in ("??", "[missing", "\\includegraphics", "Overfull", "DRAFT"):
        if marker in txt:
            print(f"    NOTE marker '{marker}' found in extracted text")
    return len(hc) + len(ht), len(hr)


def raw_pdf_bytes(path):
    return Path(path).read_bytes().decode("latin-1", errors="replace")


def main():
    root = Path(".")
    crit = rev = 0
    print("=" * 78)
    print("SUBMISSION HYGIENE AUDIT")
    print("=" * 78)
    missing = [f for f in ZIP_CONTENTS if not (root / f).exists()]
    if missing:
        print(f"\n!! MISSING INTENDED FILES: {missing}")
        crit += len(missing)

    for name in ZIP_CONTENTS:
        p = root / name
        if not p.exists():
            continue
        print(f"\n### {name}  ({p.stat().st_size:,} bytes)")
        if name.endswith(".ipynb"):
            a, b = audit_notebook(p)
        elif name.endswith(".pdf"):
            a, b = audit_pdf(p)
        elif p.suffix in {".py", ".md", ".txt"}:
            a, b = audit_text_file(p)
        else:
            print("    binary data file, not text-scanned")
            a = b = 0
        crit += a
        rev += b

    print("\n### filenames")
    # "test" is deliberately absent: a test partition is a core concept here, so
    # results/p2_2_test_comparison.csv is a correct name, not a scratch file.
    bad_names = [f for f in ZIP_CONTENTS
                 if re.search(r"(?i)(final_final|\btmp\b|\btemp\b|scratch|debug|"
                              r"claude|generated|_new\b|_old\b|\bcopy\b|backup|"
                              r"v\d+_final)", Path(f).name)]
    print(f"    unprofessional filenames: {bad_names or 'none'}")
    crit += len(bad_names)

    print("\n### files in the working folder that are NOT going into the ZIP")
    for p in sorted(root.rglob("*")):
        rel = p.relative_to(root).as_posix()
        if p.is_dir() or rel in ZIP_CONTENTS:
            continue
        print(f"    excluded: {rel}")

    print("\n" + "=" * 78)
    print(f"CRITICAL findings: {crit}      REVIEW findings: {rev}")
    print("=" * 78)
    return crit


if __name__ == "__main__":
    sys.exit(1 if main() else 0)
